# coding=utf-8

import gameclasses
from gameclasses import Game
from gameclasses import Org

gamedata = [

    ## First section corresponding to the TEG archive.
    
    Game(id = 1,
         title = "Gunbee F-99: The Kidnapping of Lady Akiko",
         developer = [2],
         publisher = [8],
         release_date = "1999",
         platforms = "Amiga",
         technologies = None,
         genre = "Vertical Shooter",
         dev_time = "16",
         distribution = "Retail",
         url = "http://www.tegperu.org/teg1995/gunbee/gunbee.htm",
         game_category = "Commercial"),

    Game(id = 2,
         title = "The King of Peru 2: The Final Mecha",
         developer = [2],
         publisher = None,
         release_date = "2001-12-13",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Fighting",
         dev_time = "6",
         distribution = "Retail",
         url = "http://www.tegperu.org/teg2000/kop2/index.asp",
         game_category = "Commercial"),

    Game(id = 3,
         title = "Samba de Oruga",
         developer = [2],
         publisher = [2],
         release_date = "2003",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Retail",
         url = "http://www.tegperu.org/teg2000/sambadeoruga/index.asp",
         game_category = "Commercial"),

    Game(id = 4,
         title = "Aventuras D'Onofrio",
         developer = [9],
         publisher = None,
         release_date = "1989",
         platforms = "Atari 2600",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Advergame"),

    Game(id = 5,
         title = "Varidiam ED-109",
         developer = [2],
         publisher = None,
         release_date = "1997",
         platforms = "Amiga",
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Hack,Conversion"),

    Game(id = 6,
         title = "Amibee",
         developer = [2],
         publisher = None,
         release_date = "1997",
         platforms = "Amiga",
         technologies = None,
         genre = "Vertical Shooter",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Hack,Conversion"),

    Game(id = 7,
         title = "La Tercera Vuelta",
         developer = [2],
         publisher = None,
         release_date = "2000-5-12",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Shooter",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/3vuelta/default.asp",
         game_category = "Noncommercial"),

    Game(id = 8,
         title = "Sokobug",
         developer = [3],
         publisher = None,
         release_date = "2000",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Noncommercial"),

    Game(id = 9,
         title = "Sokobug 2",
         developer = [3],
         publisher = None,
         release_date = "2000",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Noncommercial"),

    Game(id = 10,
         title = "El Gato Volador",
         developer = [2],
         publisher = None,
         release_date = "2001-2-8",
         platforms = "Windows,PC",
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/gato/gato.htm",
         game_category = "Noncommercial"),

    Game(id = 11,
         title = "Snakes",
         developer = [4],
         publisher = None,
         release_date = "2001-2-8",
         platforms = "PC",
         technologies = "C/C++",
         genre = "Arcade",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Localized,Noncommercial"),

    Game(id = 12,
         title = "The King of Peru 2001",
         developer = [2],
         publisher = None,
         release_date = "2001-5-22",
         platforms = "Windows,PC",
         technologies = "C/C++",
         genre = "Fighting",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/kop2k1/kop2k1.asp",
         game_category = "Noncommercial"),
    
    Game(id = 13,
         title = "Frogger Mambo",
         developer = [2],
         publisher = None,
         release_date = "2003",
         platforms = "Windows,PC",
         technologies = "C/C++",
         genre = "Arcade",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/frogger/default.asp",
         game_category = "Noncommercial"),

    Game(id = 14,
         title = "Dog Daze Revolution",
         developer = [2],
         publisher = None,
         release_date = "2004-4-1",
         platforms = "Windows,PC",
         technologies = "C/C++",
         genre = "Arcade",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/dogdaze/default.asp",
         game_category = "Remake,Noncommercial"),

    ## End section corresponding to TEG archive.

    Game(id = 15,
         title = "Crazy Combi",
         developer = [5],
         publisher = [5],
         release_date = "2009-6-24",
         platforms = "Facebook",
         technologies = "Flash",
         genre = "Arcade",
         dev_time = None,
         distribution = "Social",
         url = "https://apps.facebook.com/crazycombi/",
         game_category = "Social,Casual"),

    Game(id = 16,
         title = "1814: La Rebelion del Cusco",
         developer = [6],
         publisher = [6],
         release_date = "2012",
         platforms = None,
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = None,
         url = None,
         game_category = "Learning"),

    Game(id = 17,
         title = "Charapita Flyers",
         developer = [19],
         publisher = [19],
         release_date = "2013",
         platforms = None,
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = "Digital",
         url = None,
         game_category = "Casual"),

    Game(id = 18,
         title = "Inka Madness",
         developer = [7],
         publisher = [7],
         release_date = "2013",
         platforms = None,
         technologies = None,
         genre = "Platformer",
         dev_time = None,
         distribution = "Digital",
         url = None,
         game_category = "Casual"),

    Game(id = 19,
         title = "Tadeo in the Lost Inca Temple",
         developer = [7],
         publisher = [7],
         release_date = "2013",
         platforms = None,
         technologies = None,
         genre = "Platformer",
         dev_time = None,
         distribution = "Digital",
         url = "http://www.magiadigital.com/principal/categoria/tadeo-in-the-lost-inca-temple/169/c-169",
         game_category = "Casual"),

    Game(id = 20,
         title = "Tickle Tickle Big Fat Santa",
         developer = [20],
         publisher = [20],
         release_date = "2012-12-25",
         platforms = "Web",
         technologies = "Flash",
         genre = "Platformer",
         dev_time = None,
         distribution = "Digital",
         url = "http://www.newgrounds.com/portal/view/608331",
         game_category = "Casual"),

    Game(id = 21,
         title = "Palomilla Hunter",
         developer = [20],
         publisher = [20],
         release_date = None,
         platforms = None,
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = None,
         url = None,
         game_category = None),

    Game(id = 21,
         title = "Monster X",
         developer = [20],
         publisher = [20],
         release_date = None,
         platforms = None,
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = None,
         url = None,
         game_category = None)

]
