# coding=utf-8

import gameclasses
from gameclasses import Game
from gameclasses import Org

gamedata = [

    ## First section corresponding to the TEG archive.
    
    Game(title = "Gunbee F-99: The Kidnapping of Lady Akiko",
         developer = "Twin Eagles Group",
         publisher = "APC&TCP",
         release_date = "1999",
         platforms = "Amiga",
         technologies = None,
         genre = "Vertical Shooter",
         dev_time = "16",
         distribution = "Retail",
         url = "http://www.tegperu.org/teg1995/gunbee/gunbee.htm",
         game_category = "Commercial"),

    Game(title = "The King of Peru 2: The Final Mecha",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "2001-12-13",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Fighting",
         dev_time = "6",
         distribution = "Retail",
         url = "http://www.tegperu.org/teg2000/kop2/index.asp",
         game_category = "Commercial"),

    Game(title = "Samba de Oruga",
         developer = "Twin Eagles Group",
         publisher = "Twin Eagles Group",
         release_date = "2003",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Retail",
         url = "http://www.tegperu.org/teg2000/sambadeoruga/index.asp",
         game_category = "Commercial"),

    Game(title = "Aventuras D'Onofrio",
         developer = "SISTAP,Harley O'Brien",
         publisher = None,
         release_date = "1989",
         platforms = "Atari 2600",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Advergame"),

    Game(title = "Varidiam ED-109",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "1997",
         platforms = "Amiga",
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Hack,Conversion"),

    Game(title = "Amibee",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "1997",
         platforms = "Amiga",
         technologies = None,
         genre = "Vertical Shooter",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Hack,Conversion"),

    Game(title = "La Tercera Vuelta",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "2000-5-12",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Shooter",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/3vuelta/default.asp",
         game_category = "Noncommercial"),

    Game(title = "Sokobug",
         developer = "Bugtronix",
         publisher = None,
         release_date = "2000",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Noncommercial"),

    Game(title = "Sokobug 2",
         developer = "Bugtronix",
         publisher = None,
         release_date = "2000",
         platforms = "Windows,PC",
         technologies = None,
         genre = "Puzzle",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Noncommercial"),

    Game(title = "El Gato Volador",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "2001-2-8",
         platforms = "Windows,PC",
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/gato/gato.htm",
         game_category = "Noncommercial"),

    Game(title = "Snakes",
         developer = "JLDL Software",
         publisher = None,
         release_date = "2001-2-8",
         platforms = "PC",
         technologies = "C/C++",
         genre = "Arcade",
         dev_time = None,
         distribution = "Freeware",
         url = None,
         game_category = "Localized,Noncommercial"),

    Game(title = "The King of Peru 2001",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "2001-5-22",
         platforms = "Windows,PC",
         technologies = "C/C++",
         genre = "Fighting",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/kop2k1/kop2k1.asp",
         game_category = "Noncommercial"),
    
    Game(title = "Frogger Mambo",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "2003",
         platforms = "Windows,PC",
         technologies = "C/C++",
         genre = "Arcade",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/frogger/default.asp",
         game_category = "Noncommercial"),

    Game(title = "Dog Daze Revolution",
         developer = "Twin Eagles Group",
         publisher = None,
         release_date = "2004-4-1",
         platforms = "Windows,PC",
         technologies = "C/C++",
         genre = "Arcade",
         dev_time = None,
         distribution = "Freeware",
         url = "http://www.tegperu.org/teg2000/dogdaze/default.asp",
         game_category = "Remake,Noncommercial"),

    ## End section corresponding to TEG archive.

    Game(title = "Crazy Combi",
         developer = "Inventarte.net",
         publisher = None,
         release_date = "2009-6-24",
         platforms = "Facebook",
         technologies = "Flash",
         genre = "Arcade",
         dev_time = None,
         distribution = "Social",
         url = "https://apps.facebook.com/crazycombi/",
         game_category = "Social,Casual"),

    Game(title = "1814: La Rebelión del Cusco",
         developer = "Grupo Avatar PUCP",
         publisher = None,
         release_date = "2012",
         platforms = None,
         technologies = None,
         genre = None,
         dev_time = None,
         distribution = None,
         url = None,
         game_category = "Learning")    

]
