# coding=utf-8

import gameclasses
from gameclasses import Game
from gameclasses import Org


orgdata = [

    Org(id = 1,
        name = "Bamtang",
        start_date = 2003,
        end_date = None,
        size = 40,
        location = "San Isidro, Lima",
        url = "http://www.bamtang.com",
        email = "info@bamtang.com"),

    Org(id = 2,
        name = "Twin Eagles Group",
        start_date = 1989,
        end_date = 2003,
        size = None,
        location = "Lima",
        url = "http://www.tegperu.org",
        email = None),

    Org(id = 3,
        name = "Bugtronix",
        start_date = None,
        end_date = None,
        size = None,
        location = "Lima",
        url = None,
        email = None),

    Org(id = 4,
        name = "JLDL Software",
        start_date = None,
        end_date = None,
        size = None,
        location = "Lima",
        url = None,
        email = None),

    Org(id = 5,
        name = "Inventarte.net",
        start_date = None,
        end_date = None,
        size = None,
        location = "Lima",
        url = None,
        email = None),

    Org(id = 6,
        name = "Grupo Avatar PUCP",
        start_date = None,
        end_date = None,
        size = None,
        location = "San Miguel, Lima",
        url = None,
        email = None),

    Org(id = 7,
        name = "Pariwana Studios",
        start_date = None,
        end_date = None,
        size = None,
        location = "Miraflores, Lima",
        url = "http://www.magiadigital.com/principal/categoria/pariwana-studios/167/c-167",
        email = None),

    Org(id = 8,
        name = "APC&TCP",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 9,
        name = "SISTAP",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 10,
        name = "ArtiGames",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 11,
        name = "LEAP Game Studios",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 12,
        name = "Owson",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 13,
        name = "Plop!",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 14,
        name = "Kybalion",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 15,
        name = "Huayna Picchu Studios",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 16,
        name = "3S Games",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 17,
        name = "QuickDev",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 18,
        name = "FunBox",
        start_date = None,
        end_date = None,
        size = None,
        location = None,
        url = None,
        email = None),

    Org(id = 19,
        name = "Iquitos Play",
        start_date = "2013",
        end_date = None,
        size = None,
        location = "Iquitos",
        url = "http://www.iquitosplay.com/",
        email = None),

    Org(id = 20,
        name = "Boneless",
        start_date = "2012",
        end_date = None,
        size = 4,
        location = "Lima",
        url = "http://www.theboneless.com/",
        email = None)

]